
os: 'linux'
dist: 'bionic'
sudo: false
language: 'php'
php:
    - '8.1.0'

cache:
    directories:
        - '$HOME/.composer/cache'

before_install:
    - 'export COMPOSER_NO_INTERACTION=1'
    - 'export COMPOSER_DISABLE_XDEBUG_WARN=1'

install:
    - 'composer install --no-progress'

before_script:
    - echo 'error_reporting = E_ALL & ~E_DEPRECATED' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
    - 'bin/phpunit'

after_success:
    - 'bash <(curl -s https://codecov.io/bash)'

notifications:
    email: false
